/**
 * Hospitality AI Copilot™ — Test Fixtures.
 *
 * Simulated Knowledge, Memory, and Heart Pulse Events for validating the
 * Copilot pipeline without a live database.
 *
 * These fixtures mirror the certified architecture's data shapes:
 *   - KnowledgeEntity (validated Hospitality Knowledge™)
 *   - HospitalityMemoryEntity (Hospitality Memory™)
 *   - OperationalEvent (Heart Pulse™)
 *
 * Provenance chains are intact: Knowledge → Memory → Events.
 */

import type { KnowledgeEntity } from '@/lib/hospitality-knowledge/types'
import type { HospitalityMemoryEntity } from '@/lib/hospitality-memory/types'
import type { OperationalEvent } from '@/lib/intelligence/types'

// ============================================================================
// Heart Pulse Events (foundation of the provenance chain)
// ============================================================================

const NOW = new Date('2026-07-23T19:30:00Z')
const ONE_HOUR = 60 * 60 * 1000
const ONE_DAY = 24 * ONE_HOUR

export const TEST_EVENTS: OperationalEvent[] = [
  {
    id: 'evt_001',
    timestamp: new Date(NOW.getTime() - 2 * ONE_HOUR).toISOString(),
    type: 'order_fired',
    category: 'kitchen',
    orderId: 'ord_1001',
    orderNumber: '1001',
    tableId: 'tbl_05',
    tableNumber: '5',
    staffId: 'staff_chef_01',
    staffName: 'Chef Andre',
    stationId: 'station_grill',
    stationName: 'Grill',
    data: { items: 4, ticketTime: 18 },
  },
  {
    id: 'evt_002',
    timestamp: new Date(NOW.getTime() - 2 * ONE_HOUR + 18 * 60000).toISOString(),
    type: 'order_served',
    category: 'kitchen',
    orderId: 'ord_1001',
    orderNumber: '1001',
    tableId: 'tbl_05',
    tableNumber: '5',
    staffId: 'staff_server_02',
    staffName: 'Maria',
    data: { ticketTime: 18, items: 4 },
  },
  {
    id: 'evt_003',
    timestamp: new Date(NOW.getTime() - 90 * 60000).toISOString(),
    type: 'table_seated',
    category: 'service',
    tableId: 'tbl_12',
    tableNumber: '12',
    staffId: 'staff_host_01',
    staffName: 'James',
    data: { partySize: 4, greetingTime: 45 },
  },
  {
    id: 'evt_004',
    timestamp: new Date(NOW.getTime() - 60 * 60000).toISOString(),
    type: 'order_placed',
    category: 'service',
    orderId: 'ord_1002',
    orderNumber: '1002',
    tableId: 'tbl_12',
    tableNumber: '12',
    staffId: 'staff_server_03',
    staffName: 'Sarah',
    data: { items: 6, orderValue: 45000, upsellAttempted: true },
  },
  {
    id: 'evt_005',
    timestamp: new Date(NOW.getTime() - 45 * 60000).toISOString(),
    type: 'inventory_check',
    category: 'inventory',
    staffId: 'staff_inv_01',
    staffName: 'Patricia',
    data: { item: 'chicken_breast', onHand: 12, parLevel: 30, variance: -18 },
  },
  {
    id: 'evt_006',
    timestamp: new Date(NOW.getTime() - 30 * 60000).toISOString(),
    type: 'payment_received',
    category: 'payment',
    orderId: 'ord_1001',
    paymentId: 'pay_001',
    data: { amount: 32000, method: 'card', tip: 4000 },
  },
  {
    id: 'evt_007',
    timestamp: new Date(NOW.getTime() - 25 * 60000).toISOString(),
    type: 'customer_feedback',
    category: 'service',
    customerId: 'cust_001',
    data: { rating: 4, comment: 'Good food but slow service', npsScore: 7 },
  },
  {
    id: 'evt_008',
    timestamp: new Date(NOW.getTime() - 15 * 60000).toISOString(),
    type: 'staff_clockin',
    category: 'staff',
    staffId: 'staff_server_04',
    staffName: 'Grace',
    data: { shift: 'dinner', onTime: true },
  },
  {
    id: 'evt_009',
    timestamp: new Date(NOW.getTime() - 10 * 60000).toISOString(),
    type: 'order_fired',
    category: 'kitchen',
    orderId: 'ord_1003',
    orderNumber: '1003',
    tableId: 'tbl_08',
    tableNumber: '8',
    data: { items: 3, ticketTime: 22 },
  },
  {
    id: 'evt_010',
    timestamp: new Date(NOW.getTime() - 5 * 60000).toISOString(),
    type: 'inventory_low_stock_alert',
    category: 'inventory',
    data: { item: 'fish_tilapia', onHand: 5, parLevel: 20, severity: 'high' },
  },
  {
    id: 'evt_011',
    timestamp: new Date(NOW.getTime() - 3 * ONE_DAY).toISOString(),
    type: 'order_fired',
    category: 'kitchen',
    orderId: 'ord_0950',
    data: { items: 5, ticketTime: 25 },
  },
  {
    id: 'evt_012',
    timestamp: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString(),
    type: 'customer_feedback',
    category: 'service',
    customerId: 'cust_002',
    data: { rating: 5, comment: 'Excellent experience', npsScore: 9 },
  },
]

// ============================================================================
// Hospitality Memory (built from Heart Pulse events)
// ============================================================================

export const TEST_MEMORIES: HospitalityMemoryEntity[] = [
  {
    id: 'mem_001',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_mem_001',
    title: 'Friday dinner ticket times exceed 20 minutes during peak',
    description: 'Kitchen ticket times consistently exceed 20 minutes during Friday dinner peak (19:00-21:00), affecting 60% of orders in that window.',
    category: 'kitchen',
    status: 'confirmed',
    confidence: 'high',
    confidenceScore: 0.85,
    firstObserved: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
    lastObserved: new Date(NOW.getTime() - 2 * ONE_HOUR).toISOString(),
    observationCount: 24,
    reinforcementCount: 20,
    contradictionCount: 2,
    businessImpact: 'Guest dissatisfaction and slower table turnover',
    impactLevel: 'high',
    recommendedAction: 'Add a third cook to the grill station on Friday dinner shifts',
    actionTaken: false,
    relatedMemoryIds: ['mem_002'],
    context: { dayOfWeek: ['Friday'], timeOfDay: ['evening'], tags: ['peak', 'ticket_time'] },
    tags: ['kitchen', 'ticket_time', 'friday', 'peak'],
    provenance: {
      originEventIds: ['evt_001', 'evt_009', 'evt_011'],
      originModules: ['kitchen-intelligence'],
      formationRule: 'ticket_time_pattern_detection',
      formationRuleVersion: '1.0',
      observationRefs: [
        { id: 'obs_001', eventId: 'evt_001', eventType: 'order_fired', timestamp: new Date(NOW.getTime() - 2 * ONE_HOUR).toISOString(), sourceModule: 'kitchen-intelligence', evidence: 'Ticket time 18min on Friday 19:30', polarity: 1, impactScore: 0.7, context: { dayOfWeek: ['Friday'] } },
        { id: 'obs_002', eventId: 'evt_009', eventType: 'order_fired', timestamp: new Date(NOW.getTime() - 10 * 60000).toISOString(), sourceModule: 'kitchen-intelligence', evidence: 'Ticket time 22min on Friday 19:20', polarity: 1, impactScore: 0.8, context: { dayOfWeek: ['Friday'] } },
        { id: 'obs_003', eventId: 'evt_011', eventType: 'order_fired', timestamp: new Date(NOW.getTime() - 3 * ONE_DAY).toISOString(), sourceModule: 'kitchen-intelligence', evidence: 'Ticket time 25min previous Friday', polarity: 1, impactScore: 0.8, context: { dayOfWeek: ['Friday'] } },
      ],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
    },
    createdAt: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 2 * ONE_HOUR).toISOString(),
  },
  {
    id: 'mem_002',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_mem_002',
    title: 'Service greeting times exceed 60 seconds during peak',
    description: 'Host greeting times consistently exceed 60 seconds during dinner peak, leading to perceived service slowness.',
    category: 'service',
    status: 'confirmed',
    confidence: 'high',
    confidenceScore: 0.82,
    firstObserved: new Date(NOW.getTime() - 21 * ONE_DAY).toISOString(),
    lastObserved: new Date(NOW.getTime() - 90 * 60000).toISOString(),
    observationCount: 18,
    reinforcementCount: 15,
    contradictionCount: 1,
    businessImpact: 'Lower NPS scores and slower first impression',
    impactLevel: 'medium',
    recommendedAction: 'Assign a dedicated greeter during peak hours',
    actionTaken: false,
    relatedMemoryIds: ['mem_001'],
    context: { dayOfWeek: ['Friday', 'Saturday'], timeOfDay: ['evening'], tags: ['greeting', 'peak'] },
    tags: ['service', 'greeting_time', 'peak'],
    provenance: {
      originEventIds: ['evt_003'],
      originModules: ['service-intelligence'],
      formationRule: 'greeting_time_pattern_detection',
      formationRuleVersion: '1.0',
      observationRefs: [
        { id: 'obs_004', eventId: 'evt_003', eventType: 'table_seated', timestamp: new Date(NOW.getTime() - 90 * 60000).toISOString(), sourceModule: 'service-intelligence', evidence: 'Greeting time 45s on Friday 19:00', polarity: 0, impactScore: 0.5, context: { dayOfWeek: ['Friday'] } },
      ],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
    },
    createdAt: new Date(NOW.getTime() - 21 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 90 * 60000).toISOString(),
  },
  {
    id: 'mem_003',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_mem_003',
    title: 'Chicken breast inventory variance exceeds 50% on weekends',
    description: 'Chicken breast inventory shows consistent negative variance of 50%+ on weekends, indicating over-usage or waste.',
    category: 'inventory',
    status: 'confirmed',
    confidence: 'high',
    confidenceScore: 0.88,
    firstObserved: new Date(NOW.getTime() - 45 * ONE_DAY).toISOString(),
    lastObserved: new Date(NOW.getTime() - 45 * 60000).toISOString(),
    observationCount: 12,
    reinforcementCount: 11,
    contradictionCount: 0,
    businessImpact: 'Food cost overrun and potential stockouts',
    impactLevel: 'high',
    recommendedAction: 'Review portioning standards and investigate waste',
    actionTaken: false,
    relatedMemoryIds: [],
    context: { dayOfWeek: ['Saturday', 'Sunday'], tags: ['variance', 'chicken'] },
    tags: ['inventory', 'variance', 'chicken', 'weekend'],
    provenance: {
      originEventIds: ['evt_005'],
      originModules: ['inventory-intelligence'],
      formationRule: 'inventory_variance_pattern_detection',
      formationRuleVersion: '1.0',
      observationRefs: [
        { id: 'obs_005', eventId: 'evt_005', eventType: 'inventory_check', timestamp: new Date(NOW.getTime() - 45 * 60000).toISOString(), sourceModule: 'inventory-intelligence', evidence: 'Variance -18 units vs par 30', polarity: -1, impactScore: 0.8, context: {} },
      ],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
    },
    createdAt: new Date(NOW.getTime() - 45 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 45 * 60000).toISOString(),
  },
  {
    id: 'mem_004',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_mem_004',
    title: 'Customer NPS declining over last 30 days',
    description: 'Customer NPS has declined from 8.2 to 7.1 over the last 30 days, correlated with slower service times.',
    category: 'customer',
    status: 'confirmed',
    confidence: 'high',
    confidenceScore: 0.79,
    firstObserved: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
    lastObserved: new Date(NOW.getTime() - 25 * 60000).toISOString(),
    observationCount: 45,
    reinforcementCount: 38,
    contradictionCount: 5,
    businessImpact: 'Customer retention risk and negative word-of-mouth',
    impactLevel: 'high',
    recommendedAction: 'Prioritize service speed improvements and staff training',
    actionTaken: false,
    relatedMemoryIds: ['mem_002'],
    context: { tags: ['nps', 'satisfaction', 'trend'] },
    tags: ['customer', 'nps', 'satisfaction', 'declining'],
    provenance: {
      originEventIds: ['evt_007', 'evt_012'],
      originModules: ['customer-intelligence'],
      formationRule: 'nps_trend_detection',
      formationRuleVersion: '1.0',
      observationRefs: [
        { id: 'obs_006', eventId: 'evt_007', eventType: 'customer_feedback', timestamp: new Date(NOW.getTime() - 25 * 60000).toISOString(), sourceModule: 'customer-intelligence', evidence: 'NPS 7, comment: slow service', polarity: -1, impactScore: 0.7, context: {} },
        { id: 'obs_007', eventId: 'evt_012', eventType: 'customer_feedback', timestamp: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString(), sourceModule: 'customer-intelligence', evidence: 'NPS 9, comment: excellent', polarity: 1, impactScore: 0.5, context: {} },
      ],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
    },
    createdAt: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 25 * 60000).toISOString(),
  },
  {
    id: 'mem_005',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_mem_005',
    title: 'Friday dinner requires 3 kitchen staff to maintain 15-minute ticket times',
    description: 'Empirical analysis shows that 3 kitchen staff on Friday dinner shifts maintains ticket times under 15 minutes.',
    category: 'kitchen',
    status: 'business_rule',
    confidence: 'very_high',
    confidenceScore: 0.92,
    firstObserved: new Date(NOW.getTime() - 60 * ONE_DAY).toISOString(),
    lastObserved: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString(),
    observationCount: 8,
    reinforcementCount: 8,
    contradictionCount: 0,
    businessImpact: 'Maintains service quality during peak',
    impactLevel: 'high',
    recommendedAction: 'Schedule 3 kitchen staff for every Friday dinner',
    actionTaken: true,
    relatedMemoryIds: ['mem_001'],
    context: { dayOfWeek: ['Friday'], timeOfDay: ['evening'], tags: ['staffing', 'rule'] },
    tags: ['kitchen', 'staffing', 'friday', 'rule'],
    provenance: {
      originEventIds: ['evt_001', 'evt_011'],
      originModules: ['kitchen-intelligence'],
      formationRule: 'staffing_threshold_detection',
      formationRuleVersion: '1.0',
      observationRefs: [
        { id: 'obs_008', eventId: 'evt_001', eventType: 'order_fired', timestamp: new Date(NOW.getTime() - 2 * ONE_HOUR).toISOString(), sourceModule: 'kitchen-intelligence', evidence: '2 staff → 18min ticket', polarity: -1, impactScore: 0.7, context: {} },
      ],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
    },
    createdAt: new Date(NOW.getTime() - 60 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString(),
  },
]

// ============================================================================
// Hospitality Knowledge (validated from multiple memories)
// ============================================================================

export const TEST_KNOWLEDGE: KnowledgeEntity[] = [
  {
    id: 'kno_001',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_kno_001',
    title: 'Friday dinner peak requires additional kitchen staffing',
    summary: 'Friday dinner service requires 3 kitchen staff to maintain 15-minute ticket times',
    description: 'Analysis of 8 weeks of Friday dinner shifts shows that 3 kitchen staff maintain ticket times under 15 minutes, while 2 staff result in 18-25 minute ticket times affecting 60% of orders.',
    category: 'kitchen',
    statement: 'Friday dinner service requires 3 kitchen staff to maintain 15-minute ticket times',
    status: 'canonical',
    confidence: 'very_high',
    confidenceScore: 0.92,
    supportingMemoryCount: 2,
    contradictingMemoryCount: 0,
    totalEvidenceCount: 32,
    firstObserved: new Date(NOW.getTime() - 60 * ONE_DAY).toISOString(),
    lastValidated: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString(),
    establishedAt: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString(),
    businessImpact: 'Maintains service quality and guest satisfaction during peak',
    impactLevel: 'high',
    applicability: {
      scope: 'temporal',
      conditions: ['dayOfWeek:Friday', 'timeOfDay:evening'],
    },
    recommendedActions: [
      { action: 'Schedule 3 kitchen staff for every Friday dinner shift', priority: 'high', expectedOutcome: 'Ticket times maintained under 15 minutes', basedOn: '8 weeks of empirical data' },
      { action: 'Cross-train one server as backup grill cook', priority: 'medium', expectedOutcome: 'Flexible staffing during unexpected absences', basedOn: 'Staffing resilience best practice' },
    ],
    operationalRules: ['Friday dinner = 3 kitchen staff minimum', 'Grill station priority during 19:00-21:00'],
    relatedKnowledgeIds: ['kno_002'],
    tags: ['kitchen', 'staffing', 'friday', 'peak', 'ticket_time'],
    provenance: {
      originMemoryIds: ['mem_001', 'mem_005'],
      originEventIds: ['evt_001', 'evt_009', 'evt_011'],
      originModules: ['kitchen-intelligence'],
      formationPipeline: [],
      memoryRefs: [
        { memoryId: 'mem_001', memoryTitle: 'Friday dinner ticket times exceed 20 minutes during peak', memoryCategory: 'kitchen', memoryConfidence: 0.85, memoryStatus: 'confirmed', contribution: 'Establishes the problem pattern', weight: 0.7, firstContributed: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(), lastContributed: new Date(NOW.getTime() - 2 * ONE_HOUR).toISOString() },
        { memoryId: 'mem_005', memoryTitle: 'Friday dinner requires 3 kitchen staff', memoryCategory: 'kitchen', memoryConfidence: 0.92, memoryStatus: 'business_rule', contribution: 'Establishes the solution threshold', weight: 0.9, firstContributed: new Date(NOW.getTime() - 60 * ONE_DAY).toISOString(), lastContributed: new Date(NOW.getTime() - 7 * ONE_DAY).toISOString() },
      ],
      crossRefs: [],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
      formationRule: 'multi_memory_synthesis',
      formationRuleVersion: '1.0',
      validationRule: 'cross_memory_validation',
      validationRuleVersion: '1.0',
    },
    createdAt: new Date(NOW.getTime() - 60 * ONE_DAY).toISOString(),
  },
  {
    id: 'kno_002',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_kno_002',
    title: 'Service speed is the primary driver of NPS decline',
    summary: 'Customer NPS decline from 8.2 to 7.1 is correlated with slower service greeting and ticket times',
    description: 'Cross-analysis of customer feedback and service timing data shows that 70% of NPS decline is attributable to slower service greeting times and kitchen ticket times during peak hours.',
    category: 'service',
    statement: 'Service speed improvements are the highest-leverage intervention for NPS recovery',
    status: 'established',
    confidence: 'high',
    confidenceScore: 0.84,
    supportingMemoryCount: 2,
    contradictingMemoryCount: 0,
    totalEvidenceCount: 63,
    firstObserved: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
    lastValidated: new Date(NOW.getTime() - 1 * ONE_DAY).toISOString(),
    establishedAt: new Date(NOW.getTime() - 14 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 1 * ONE_DAY).toISOString(),
    businessImpact: 'Customer retention and word-of-mouth at risk',
    impactLevel: 'high',
    applicability: {
      scope: 'business',
      conditions: ['timeOfDay:evening'],
    },
    recommendedActions: [
      { action: 'Assign dedicated greeter during peak hours', priority: 'high', expectedOutcome: 'Reduce greeting time to under 30 seconds', basedOn: 'Service benchmark data' },
      { action: 'Implement kitchen staffing rule for peak shifts', priority: 'high', expectedOutcome: 'Reduce ticket times to under 15 minutes', basedOn: 'Kitchen performance analysis' },
    ],
    operationalRules: ['Peak hours require dedicated greeter', 'Kitchen staffing scales with cover count'],
    relatedKnowledgeIds: ['kno_001'],
    tags: ['service', 'nps', 'customer', 'speed', 'peak'],
    provenance: {
      originMemoryIds: ['mem_002', 'mem_004'],
      originEventIds: ['evt_003', 'evt_007', 'evt_012'],
      originModules: ['service-intelligence', 'customer-intelligence'],
      formationPipeline: [],
      memoryRefs: [
        { memoryId: 'mem_002', memoryTitle: 'Service greeting times exceed 60 seconds during peak', memoryCategory: 'service', memoryConfidence: 0.82, memoryStatus: 'confirmed', contribution: 'Establishes greeting time problem', weight: 0.6, firstContributed: new Date(NOW.getTime() - 21 * ONE_DAY).toISOString(), lastContributed: new Date(NOW.getTime() - 90 * 60000).toISOString() },
        { memoryId: 'mem_004', memoryTitle: 'Customer NPS declining over last 30 days', memoryCategory: 'customer', memoryConfidence: 0.79, memoryStatus: 'confirmed', contribution: 'Establishes NPS trend and correlation', weight: 0.8, firstContributed: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(), lastContributed: new Date(NOW.getTime() - 25 * 60000).toISOString() },
      ],
      crossRefs: [],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
      formationRule: 'cross_domain_synthesis',
      formationRuleVersion: '1.0',
      validationRule: 'correlation_validation',
      validationRuleVersion: '1.0',
    },
    createdAt: new Date(NOW.getTime() - 30 * ONE_DAY).toISOString(),
  },
  {
    id: 'kno_003',
    businessId: 'biz_001',
    version: 1,
    fingerprint: 'fp_kno_003',
    title: 'Weekend inventory variance indicates portioning or waste issue',
    summary: 'Chicken breast inventory variance of 50%+ on weekends indicates over-usage or waste',
    description: 'Consistent negative variance of 50%+ on chicken breast inventory during weekends suggests either portioning inconsistency or unrecorded waste. Cost impact estimated at 180,000 RWF/month.',
    category: 'inventory',
    statement: 'Weekend chicken breast variance requires portioning audit and waste tracking',
    status: 'established',
    confidence: 'high',
    confidenceScore: 0.88,
    supportingMemoryCount: 1,
    contradictingMemoryCount: 0,
    totalEvidenceCount: 12,
    firstObserved: new Date(NOW.getTime() - 45 * ONE_DAY).toISOString(),
    lastValidated: new Date(NOW.getTime() - 1 * ONE_DAY).toISOString(),
    establishedAt: new Date(NOW.getTime() - 21 * ONE_DAY).toISOString(),
    updatedAt: new Date(NOW.getTime() - 1 * ONE_DAY).toISOString(),
    businessImpact: '180,000 RWF/month cost overrun',
    impactLevel: 'high',
    applicability: {
      scope: 'temporal',
      conditions: ['dayOfWeek:Saturday', 'dayOfWeek:Sunday'],
    },
    recommendedActions: [
      { action: 'Conduct portioning audit on chicken breast', priority: 'high', expectedOutcome: 'Identify if portions exceed standard', basedOn: 'Variance pattern analysis' },
      { action: 'Implement waste tracking sheet at grill station', priority: 'medium', expectedOutcome: 'Quantify unrecorded waste', basedOn: 'Inventory best practice' },
    ],
    operationalRules: ['Weekend chicken breast portions = 180g standard', 'Waste sheet required at grill station'],
    relatedKnowledgeIds: [],
    tags: ['inventory', 'variance', 'chicken', 'weekend', 'cost'],
    provenance: {
      originMemoryIds: ['mem_003'],
      originEventIds: ['evt_005'],
      originModules: ['inventory-intelligence'],
      formationPipeline: [],
      memoryRefs: [
        { memoryId: 'mem_003', memoryTitle: 'Chicken breast inventory variance exceeds 50% on weekends', memoryCategory: 'inventory', memoryConfidence: 0.88, memoryStatus: 'confirmed', contribution: 'Establishes variance pattern', weight: 0.9, firstContributed: new Date(NOW.getTime() - 45 * ONE_DAY).toISOString(), lastContributed: new Date(NOW.getTime() - 45 * 60000).toISOString() },
      ],
      crossRefs: [],
      confidenceHistory: [],
      lifecycleHistory: [],
      consumerAccessHistory: [],
      formationRule: 'memory_synthesis',
      formationRuleVersion: '1.0',
      validationRule: 'variance_validation',
      validationRuleVersion: '1.0',
    },
    createdAt: new Date(NOW.getTime() - 45 * ONE_DAY).toISOString(),
  },
]

// ============================================================================
// Test Business
// ============================================================================

export const TEST_BUSINESS_ID = 'biz_001'
export const TEST_BUSINESS_NAME = 'Imboni Resto'

export const TEST_FIXTURE = {
  businessId: TEST_BUSINESS_ID,
  businessName: TEST_BUSINESS_NAME,
  knowledge: TEST_KNOWLEDGE,
  memories: TEST_MEMORIES,
  events: TEST_EVENTS,
}
